export const companyMetrics = {
  total: [
    "Acme Corp",
    "Techify",
    "GreenLeaf Ltd",
    "BrightWorks",
    "SkyNet Solutions",
    "BlueWave Inc",
    "PixelPerfect",
    "Nova Systems",
    "CloudSync",
    "EcoSmart",
    "NextGen Labs",
    "FusionWorks",
    "Vertex Global",
    "UrbanEdge",
    "PrimeTech",
    "FutureSoft",
  ],
  unique: [
    "BlueWave Inc",
    "PixelPerfect",
    "Nova Systems",
    "CloudSync",
    "EcoSmart",
  ],
  multiple: [
    "NextGen Labs",
    "FusionWorks",
    "Vertex Global",
    "UrbanEdge",
    "PrimeTech",
  ],
  consultancy: [
    "NextGen Labs",
    "FusionWorks",
    "Vertex Global",
    "UrbanEdge",
    "PrimeTech",
  ],
  training: [
    "UrbanEdge",
    "PrimeTech",
    "FutureSoft",
  ],
};
