//components/constants/organisationCategories.js
export const SECTORS = [
  'Non-Profit',
  'Private',
  'Professional Body',
  'Public',
  'Commercial',
  'Statutory Board'  
];

export const ORGANIZATION_SIZES = [
  'Government-Linked Company (GLC)',
  'Government-Linked Institution (GLI)',
  'Multinational Corporation (MNC)',
  'Small-Medium Enterprise (SME)',
  'Startup',
];

export const INDUSTRIES = [
  'Agriculture & Farming',
  'Arts & Culture',
  'Aviation & Aerospace',
  'Banking',
  'Biomedical Sciences',
  'Border Control & Immigration',
  'Community Services',
  'Consulting Services',
  'Construction & Engineering',
  'Cosmetics',
  'Defense & Security',
  'Digital & Technology',
  'Diplomatic Services',
  'Education',
  'Education (Higher)',
  'Education (Primary/Secondary)',
  'Education Technology',
  'Energy & Resources',
  'Environmental Services',
  'Financial Services',
  'Food & Beverage',
  'Healthcare & Medical',
  'Industry Associations & Chambers',
  'Information Technology',
  'Infrastructure & Utilities',
  'Innovation & Enterprise',
  'Insurance',
  'Investment & Asset Management',
  'Legal Services',
  'Manufacturing',
  'Manufacturing (Chemical/Pharma)',
  'Manufacturing (Electronics/Technology)',
  'Manufacturing (F&B/FMCG)',
  'Manufacturing (Marine/Offshore)',
  'Maritime',
  'Maritime & Shipping',
  'Media & Entertainment',
  'Pharmaceutical',
  'Professional Services',
  'Property & Real Estate',
  'Public Administration',
  'Public Safety & Security',
  'Public Services',
  'Research',
  'Research & Development',
  'Retail & Consumer',
  'Science & Technology',
  'Sports & Recreation',
  'Telecommunications',
  'Tourism & Hospitality',
  'Transportation & Logistics'
];
